import { test, expect, type Page } from '@playwright/test'

async function createTask(page: Page, title: string) {
  await page.goto('/tasks')
  await page.getByRole('button', { name: 'New task', exact: true }).click()
  await page.getByLabel('Title *', { exact: true }).fill(title)
  await page.getByRole('button', { name: 'Save task', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
}
test('task create, edit, complete, search, reload, and delete', async ({ page }) => {
  await createTask(page, 'Study Logistic Regression')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Study Logistic Regression' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit Study Logistic Regression', exact: true }).click()
  await page.getByLabel('Title *', { exact: true }).fill('Study and implement regression')
  await page.getByRole('button', { name: 'Save task', exact: true }).click()
  await page.getByRole('button', { name: 'Complete Study and implement regression', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Reopen Study and implement regression', exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Filter entries' }).selectOption('Completed')
  await page.getByRole('textbox', { name: 'Search tasks' }).fill('unmatched')
  await expect(page.getByText('No matching entries')).toBeVisible()
  await page.getByRole('textbox', { name: 'Search tasks' }).fill('')
  await page.getByRole('button', { name: 'Delete Study and implement regression', exact: true }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.reload()
  await expect(page.getByText('Your tasks start here')).toBeVisible()
})
test('export, rejected import, clear confirmation, and restore', async ({ page }) => {
  await createTask(page, 'Backup round trip')
  await page.goto('/settings')
  const downloaded = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export Data', exact: true }).click()
  const download = await downloaded
  expect(download.suggestedFilename()).toBe('personal-os-backup.json')
  const backupPath = await download.path()
  await page.getByLabel('Import Data', { exact: true }).setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"app":"personal-os","version":1,"data":{}}') })
  await expect(page.getByRole('alert')).toContainText('Unsupported backup')
  await page.goto('/tasks')
  await expect(page.getByRole('heading', { name: 'Backup round trip' })).toBeVisible()
  await page.goto('/settings')
  await page.getByRole('button', { name: 'Clear Local Data', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Clear everything' })).toBeDisabled()
  await page.getByLabel('Type CLEAR to confirm').fill('CLEAR')
  await page.getByRole('button', { name: 'Clear everything' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByLabel('Import Data', { exact: true }).setInputFiles(backupPath!)
  await page.getByRole('button', { name: 'Confirm merge' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goto('/tasks')
  await expect(page.getByRole('heading', { name: 'Backup round trip' })).toBeVisible()
})
test('study timer persists across reload and saves a real session', async ({ page }) => {
  await page.goto('/time-tracking')
  await page.getByLabel('Topic *', { exact: true }).fill('Neural networks')
  await page.getByRole('button', { name: 'Start session', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Topic *', { exact: true })).toHaveValue('Neural networks')
  await expect(page.getByRole('timer')).not.toHaveText('00:00:00')
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await page.getByRole('button', { name: 'Stop & save', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Session saved' })).toBeVisible()
  await page.goto('/study-sessions')
  await expect(page.getByRole('heading', { name: 'Neural networks' })).toBeVisible()
})
test('courses, habits, and budgets calculate from entered records', async ({ page }) => {
  await page.goto('/courses')
  await page.getByRole('button', { name: 'New course', exact: true }).click()
  await page.getByLabel('Course name *').fill('Machine Learning')
  await page.getByLabel('Topics (one per line)').fill('Python\nNumPy')
  await page.getByRole('button', { name: 'Save course', exact: true }).click()
  await page.getByLabel('Python', { exact: true }).check()
  await expect(page.getByRole('progressbar', { name: 'Machine Learning progress' })).toHaveAttribute('aria-valuenow', '50')
  await page.goto('/habits')
  await page.getByRole('button', { name: 'New habit', exact: true }).click()
  await page.getByLabel('Habit name *').fill('Daily coding')
  await page.getByRole('button', { name: 'Save habit', exact: true }).click()
  await page.getByRole('button', { name: 'Complete today', exact: true }).click()
  await expect(page.getByText('1 day streak', { exact: true })).toBeVisible()
  await page.goto('/finance/transactions')
  await page.getByRole('button', { name: 'New transaction', exact: true }).click()
  await page.getByLabel('Description *', { exact: true }).fill('Lunch')
  await page.getByLabel('Amount *', { exact: true }).fill('150')
  await page.getByLabel('Category', { exact: true }).selectOption('Food')
  await page.getByRole('button', { name: 'Save transaction', exact: true }).click()
  await page.goto('/finance/budget')
  await page.getByRole('button', { name: 'New budget', exact: true }).click()
  await page.getByLabel('Budget name *').fill('Food plan')
  await page.getByLabel('Category *', { exact: true }).selectOption('Food')
  await page.getByLabel('Monthly limit *').fill('1000')
  await page.getByRole('button', { name: 'Save budget', exact: true }).click()
  await expect(page.getByRole('progressbar', { name: 'Budget used' })).toHaveAttribute('aria-valuenow', '15')
})
test('mobile navigation, every route, theme, and offline reload', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Tasks', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Tasks', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open navigation' })).toHaveAttribute('aria-expanded', 'false')
  for (const route of ['/habits', '/time-tracking', '/courses', '/skills', '/study-sessions', '/projects', '/goals', '/finance', '/finance/transactions', '/finance/budget', '/information', '/information/ai-ml', '/information/cse', '/information/software', '/information/career', '/information/study-abroad', '/information/scholarships', '/information/competitions', '/information/hackathons', '/analytics', '/insights', '/settings', '/notes', '/read-later', '/opportunities']) {
    await page.goto(route)
    await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `${route} should fit mobile width`).toBeTruthy()
  }
  await page.getByRole('button', { name: 'Toggle light and dark theme' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.goto('/')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: 'test-results/dashboard-dark.png', fullPage: true })
  await page.evaluate(() => navigator.serviceWorker.ready)
  await context.setOffline(true)
  await page.goto('/tasks')
  await expect(page.getByRole('heading', { name: 'Tasks', exact: true })).toBeVisible()
  await createTask(page, 'Created while offline')
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Created while offline' })).toBeVisible()
  expect(errors).toEqual([])
})
test('external feeds are opt-in, tolerate provider failure, and save normalized articles', async ({ page }) => {
  let externalRequests = 0
  await page.route('https://dev.to/api/**', async route => { externalRequests++; await route.fulfill({ json: [{ id: 1, title: 'ML testing article', url: 'https://dev.to/example/ml', description: 'Fixture for provider adapter testing', tag_list: ['machinelearning'], published_at: '2026-09-13T12:00:00Z' }] }) })
  await page.route('https://hn.algolia.com/**', async route => { externalRequests++; await route.fulfill({ status: 503, body: 'Unavailable' }) })
  await page.goto('/information/ai-ml')
  await expect(page.getByText('Fresh information, on your terms')).toBeVisible()
  expect(externalRequests).toBe(0)
  await page.getByRole('button', { name: 'Fetch public updates' }).click()
  await expect(page.getByRole('heading', { name: 'ML testing article' })).toBeVisible()
  await expect(page.getByText('Hacker News / Algolia is unavailable. Try again later.')).toBeVisible()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Saved', exact: true })).toBeDisabled()
  await page.goto('/read-later')
  await expect(page.getByRole('heading', { name: 'ML testing article' })).toBeVisible()
})
