import { useState } from 'react'
import { Plus, Search, Pencil, Trash2, Check, ExternalLink, Flame, ArrowUpRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { modules, text, numeric, list, localDate, entryProgress, safeUrl, type Collection, type Entry } from '../data/model'
import { newEntry, useStore } from '../data/store'
import { daysBack, habitStats, money, duration } from '../lib/analytics'
import EntryForm from '../components/EntryForm'
import { EmptyState, Modal, PageHeading, Progress } from '../components/ui'

export default function CollectionPage({ collection }: { collection: Collection }) {
  const { data, save, remove, change } = useStore()
  const [query, setQuery] = useState(''), [filter, setFilter] = useState('All'), [sort, setSort] = useState('newest')
  const [editing, setEditing] = useState<Entry | null | undefined>(), [deleting, setDeleting] = useState<Entry | null>(null), [busy, setBusy] = useState(false)
  const module = modules[collection], today = localDate()
  const isTasks = collection === 'tasks', isHabits = collection === 'habits'
  const options = isTasks ? ['All', 'Today', 'Upcoming', 'Overdue', 'Todo', 'In Progress', 'Completed', 'Cancelled'] : module.fields.find(field => field.key === 'status' || field.key === 'type')?.options
  const visible = data[collection].filter(entry => {
    const match = Object.values(entry).join(' ').toLowerCase().includes(query.toLowerCase())
    const due = text(entry, 'dueDate'), open = !['Completed', 'Cancelled'].includes(text(entry, 'status'))
    return match && (filter === 'All' || (filter === 'Today' ? due === today && open : filter === 'Upcoming' ? due > today && open : filter === 'Overdue' ? !!due && due < today && open : entry.status === filter || entry.type === filter))
  }).sort((a, b) => sort === 'title' ? text(a, 'title').localeCompare(text(b, 'title')) : sort === 'due' ? (text(a, 'dueDate') || text(a, 'deadline') || '9999').localeCompare(text(b, 'dueDate') || text(b, 'deadline') || '9999') : sort === 'priority' ? ['High', 'Medium', 'Low'].indexOf(text(a, 'priority')) - ['High', 'Medium', 'Low'].indexOf(text(b, 'priority')) : text(b, 'createdAt').localeCompare(text(a, 'createdAt')))
  async function toggleHabit(id: string) {
    await change(current => { current.habits = current.habits.map(habit => habit.id === id ? { ...habit, completions: list(habit, 'completions').includes(today) ? list(habit, 'completions').filter(date => date !== today) : [...list(habit, 'completions'), today], updatedAt: new Date().toISOString() } : habit); return current })
  }
  async function addDeadline(entry: Entry, target: 'tasks' | 'goals') {
    const title = `${target === 'tasks' ? 'Apply: ' : ''}${text(entry, 'title')}`
    if (data[target].some(item => item.title === title)) return
    await save(target, { ...newEntry(), title, description: text(entry, 'url'), ...(target === 'tasks' ? { status: 'Todo', dueDate: text(entry, 'deadline') } : { progress: 0, deadline: text(entry, 'deadline'), category: 'Career' }), priority: 'Medium' })
  }
  return <><PageHeading eyebrow="LOCAL WORKSPACE" title={module.title} description={module.description} action={<button className="button" onClick={() => setEditing(null)}><Plus size={17} />New {module.singular}</button>} />
    <div className="toolbar"><label className="search"><Search size={17} /><input aria-label={`Search ${module.title.toLowerCase()}`} placeholder={`Search ${module.title.toLowerCase()}…`} value={query} onChange={e => setQuery(e.target.value)} /></label>{options && <select aria-label="Filter entries" value={filter} onChange={e => setFilter(e.target.value)}>{(options[0] === 'All' ? options : ['All', ...options]).map(option => <option key={option}>{option}</option>)}</select>}<select aria-label="Sort entries" value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Newest first</option><option value="title">Name A–Z</option><option value="due">Deadline</option>{isTasks && <option value="priority">Priority</option>}</select><span className="muted small">{visible.length} {visible.length === 1 ? 'entry' : 'entries'}</span></div>
    {visible.length === 0 ? <section className="panel"><EmptyState title={data[collection].length ? 'No matching entries' : `Your ${module.title.toLowerCase()} start here`} description={data[collection].length ? 'Try a different search or filter.' : `Add your first ${module.singular}. Everything is stored privately in this browser.`} action={!data[collection].length && <button className="button secondary" onClick={() => setEditing(null)}><Plus size={16} />Add {module.singular}</button>} /></section> : <div className={isTasks || collection === 'financeTransactions' || collection === 'studySessions' ? 'entry-list' : 'card-grid'}>{visible.map(entry => {
      const progress = entryProgress(entry, collection), habit = isHabits ? habitStats(entry) : null
      const spent = collection === 'financeBudgets' ? data.financeTransactions.filter(item => item.type === 'expense' && item.category === entry.category && text(item, 'date').startsWith(text(entry, 'month'))).reduce((sum, item) => sum + numeric(item, 'amount'), 0) : 0
      const url = safeUrl(text(entry, 'url') || text(entry, 'githubUrl'))
      return <article className={`panel entry ${isTasks && entry.status === 'Completed' ? 'completed' : ''}`} key={entry.id}><div className="entry-top">{isTasks && <button className={`check-button ${entry.status === 'Completed' ? 'checked' : ''}`} aria-label={`${entry.status === 'Completed' ? 'Reopen' : 'Complete'} ${entry.title}`} onClick={() => void save(collection, { ...entry, status: entry.status === 'Completed' ? 'Todo' : 'Completed' })}><Check size={15} /></button>}<div className="entry-title"><h3>{text(entry, 'title')}</h3><div className="tags">{['status', 'priority', 'category', 'type'].map(key => entry[key] && <span className={`tag ${entry[key] === 'High' || entry[key] === 'expense' ? 'warm' : ''}`} key={key}>{text(entry, key)}</span>)}{list(entry, 'tags').filter(Boolean).map((tag, index) => <span className="tag" key={index}>{tag}</span>)}</div></div><div className="entry-actions"><button className="icon-button" aria-label={`Edit ${entry.title}`} onClick={() => setEditing(entry)}><Pencil size={16} /></button><button className="icon-button" aria-label={`Delete ${entry.title}`} onClick={() => setDeleting(entry)}><Trash2 size={16} /></button></div></div>
        {entry.description && <p className="entry-description">{text(entry, 'description')}</p>}
        <div className="entry-meta">{['dueDate', 'deadline', 'date', 'month'].map(key => entry[key] && <span className={text(entry, key) < today && (key === 'dueDate' || key === 'deadline') && !['Completed', 'Cancelled', 'Closed'].includes(text(entry, 'status')) && progress < 100 ? 'error-text' : ''} key={key}>{key === 'dueDate' || key === 'deadline' ? 'Due ' : ''}{text(entry, key)}</span>)}{collection === 'financeTransactions' && <strong>{entry.type === 'income' ? '+' : '−'}{money(numeric(entry, 'amount'), data.settings.currency)}</strong>}{collection === 'studySessions' && <strong>{duration(numeric(entry, 'duration'))}</strong>}{isTasks && numeric(entry, 'estimatedDuration') > 0 && <span>{duration(numeric(entry, 'estimatedDuration'))} planned</span>}{(['course', 'skill', 'project', 'goal'] as const).map(key => {
          const target: Collection = key === 'course' ? 'courses' : key === 'skill' ? 'skills' : key === 'project' ? 'projects' : 'goals'
          const related = data[target].find(item => item.id === entry[key]); return related && <Link key={key} to={`/${target}`}>{text(related, 'title')} <ArrowUpRight size={12} /></Link>
        })}</div>
        {module.fields.some(field => field.key === 'progress') && <div className="progress-block"><div><span className="muted small">{collection === 'courses' && list(entry, 'topics').length ? 'Topic completion' : 'Progress'}</span><strong>{progress}%</strong></div><Progress value={progress} label={`${entry.title} progress`} /></div>}
        {collection === 'courses' && <div className="topic-list">{list(entry, 'topics').filter(Boolean).map((topic, index) => <label key={index}><input type="checkbox" checked={list(entry, 'completedTopics').includes(topic)} onChange={() => void save(collection, { ...entry, completedTopics: list(entry, 'completedTopics').includes(topic) ? list(entry, 'completedTopics').filter(t => t !== topic) : [...list(entry, 'completedTopics'), topic] })} />{topic}</label>)}</div>}
        {collection === 'skills' && <><p className="small muted">{text(entry, 'currentLevel')} → {text(entry, 'targetLevel')}</p>{list(entry, 'progressHistory').length > 0 && <details><summary className="small muted">Progress history</summary><ul className="history">{list(entry, 'progressHistory').slice(-12).reverse().map((point, index) => <li key={index}>{point.split('|')[0].slice(0, 10)} <strong>{point.split('|')[1]}%</strong></li>)}</ul></details>}</>}
        {habit && <><div className="habit-stats"><span><Flame size={16} />{habit.streak} day streak</span><span>{habit.week}% this week</span><span>{habit.month}% last 30 days</span></div><div className="heatmap" aria-label="Habit completions over the last 30 days">{daysBack(30).map(day => <span key={day} className={list(entry, 'completions').includes(day) ? 'done' : ''} title={`${day}: ${list(entry, 'completions').includes(day) ? 'completed' : 'not completed'}`} />)}</div><button className={`button ${list(entry, 'completions').includes(today) ? 'secondary' : ''}`} onClick={() => void toggleHabit(entry.id)}><Check size={16} />{list(entry, 'completions').includes(today) ? 'Completed today · undo' : 'Complete today'}</button></>}
        {collection === 'financeBudgets' && <><div className="progress-block"><div><span>{money(spent, data.settings.currency)} spent</span><span>of {money(numeric(entry, 'amount'), data.settings.currency)}</span></div><Progress value={spent / numeric(entry, 'amount') * 100} label="Budget used" /></div><p className={spent > numeric(entry, 'amount') ? 'error-text small' : 'small muted'}>{money(Math.abs(numeric(entry, 'amount') - spent), data.settings.currency)} {spent > numeric(entry, 'amount') ? 'over budget' : 'remaining'}</p></>}
        {url && <a className="text-link" href={url} target="_blank" rel="noreferrer">View original source <ExternalLink size={14} /></a>}
        {collection === 'opportunities' && <div className="button-row"><button className="button secondary small" disabled={data.tasks.some(item => item.title === `Apply: ${entry.title}`)} onClick={() => void addDeadline(entry, 'tasks')}>Add to tasks</button><button className="button secondary small" disabled={data.goals.some(item => item.title === entry.title)} onClick={() => void addDeadline(entry, 'goals')}>Add to goals</button></div>}
        {['projects', 'goals'].includes(collection) && <p className="small muted">{data.tasks.filter(task => task[collection === 'projects' ? 'project' : 'goal'] === entry.id).length} linked tasks{collection === 'goals' && ` · ${data.projects.filter(project => project.goal === entry.id).length} linked projects`}</p>}
        {entry.notes && <details><summary className="small muted">Notes</summary><p className="entry-description">{text(entry, 'notes')}</p></details>}
      </article>
    })}</div>}
    {editing !== undefined && <EntryForm collection={collection} entry={editing ?? undefined} onClose={() => setEditing(undefined)} />}
    {deleting && <Modal title={`Delete ${module.singular}?`} onClose={() => { if (!busy) setDeleting(null) }}><p>“{text(deleting, 'title')}” will be removed. Links to this entry will be cleared. This cannot be undone.</p><div className="form-actions"><button className="button secondary" disabled={busy} onClick={() => setDeleting(null)}>Cancel</button><button className="button danger" disabled={busy} onClick={async () => { setBusy(true); if (await remove(collection, deleting.id)) setDeleting(null); setBusy(false) }}>{busy ? 'Deleting…' : 'Delete'}</button></div></Modal>}
  </>
}
