import { lazy, Suspense, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, BookOpen, Check, CircleCheck, Clock3, Compass, Flag, Plus, Sparkles, Wallet, Zap } from 'lucide-react'
import { useStore } from '../data/store'
import { entryProgress, numeric, text } from '../data/model'
import { duration, localInsight, money, summarize } from '../lib/analytics'
import { EmptyState, PageHeading, Progress } from '../components/ui'
import EntryForm from '../components/EntryForm'

const StudyChart = lazy(() => import('../components/StudyChart'))
export default function Dashboard() {
  const { data, save } = useStore(), stats = summarize(data)
  const [adding, setAdding] = useState(false)
  const hour = new Date().getHours(), greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'
  const priorityOrder = ['High', 'Medium', 'Low']
  const focus = [...stats.open].sort((a, b) => (text(a, 'dueDate') || '9999').localeCompare(text(b, 'dueDate') || '9999') || priorityOrder.indexOf(text(a, 'priority')) - priorityOrder.indexOf(text(b, 'priority'))).slice(0, 4)
  const opportunities = data.opportunities.filter(item => item.status !== 'Closed' && (!item.deadline || text(item, 'deadline') >= stats.today)).sort((a, b) => (text(a, 'deadline') || '9999').localeCompare(text(b, 'deadline') || '9999')).slice(0, 3)
  const budget = data.financeBudgets.filter(item => item.month === stats.month).reduce((sum, item) => sum + numeric(item, 'amount'), 0)
  const deadlines = [...stats.open.map(item => ({ title: text(item, 'title'), date: text(item, 'dueDate'), to: '/tasks', kind: 'Task' })), ...stats.goals.map(item => ({ title: text(item, 'title'), date: text(item, 'deadline'), to: '/goals', kind: 'Goal' })), ...data.opportunities.filter(item => item.status !== 'Closed').map(item => ({ title: text(item, 'title'), date: text(item, 'deadline'), to: '/opportunities', kind: text(item, 'type') }))].filter(item => item.date >= stats.today).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 3)
  return <><PageHeading eyebrow={new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).toUpperCase()} title={`${greeting}${data.settings.name ? `, ${data.settings.name}` : ''}.`} description="A little clarity. A meaningful step forward." action={<button className="button" onClick={() => setAdding(true)}><Plus size={17} />Add task</button>} />
    <section className="daily-brief"><div className="brief-icon"><Zap size={22} /></div><div><span className="eyebrow">YOUR DAY, AT A GLANCE</span><p>{stats.todayTasks.filter(item => item.status !== 'Completed').length} tasks due today <span>·</span> {duration(stats.plannedMinutes)} planned <span>·</span> {stats.overdue.length} overdue <span>·</span> {opportunities.length} saved opportunities</p></div><Link to="/insights" className="brief-link">Find your focus <ArrowUpRight size={16} /></Link></section>
    <div className="stat-grid"><Stat icon={<CircleCheck size={20} />} label="Tasks completed" value={`${stats.doneToday}`} detail={`${stats.open.length} remaining overall`} accent="green" /><Stat icon={<Clock3 size={20} />} label="Study time today" value={duration(stats.studyToday)} detail={`${duration(stats.weekly.reduce((sum, item) => sum + item.minutes, 0))} in the last 7 days`} accent="blue" /><Stat icon={<Wallet size={20} />} label="Monthly savings" value={money(stats.savings, data.settings.currency)} detail="Recorded income minus expenses" accent="amber" /><Stat icon={<Flag size={20} />} label="Active goals" value={String(stats.goals.length)} detail={`${stats.goalProgress}% average goal progress`} accent="violet" /></div>
    <div className="dashboard-grid"><section className="panel focus-panel"><SectionHeading icon={<CircleCheck size={18} />} title="Your next actions" to="/tasks" label="All tasks" />{focus.length ? <div className="focus-list">{focus.map(task => <div className="focus-item" key={task.id}><button className="check-button" aria-label={`Complete ${task.title}`} onClick={() => void save('tasks', { ...task, status: 'Completed' })}><Check size={14} /></button><div><strong>{text(task, 'title')}</strong><p className="small muted">{text(task, 'dueDate') ? task.dueDate === stats.today ? 'Due today' : `Due ${task.dueDate}` : 'No deadline'}{numeric(task, 'estimatedDuration') > 0 && ` · ${duration(numeric(task, 'estimatedDuration'))}`}</p></div><span className={`tag ${task.priority === 'High' ? 'warm' : ''}`}>{text(task, 'priority') || 'Medium'}</span></div>)}</div> : <EmptyState title="A clear space to begin" description="Capture one thing you want to move forward today." action={<button className="text-link" onClick={() => setAdding(true)}>Add your first task <ArrowRight size={15} /></button>} />}<div className="panel-footer"><span className="small muted">Overall task completion</span><strong className="small">{stats.completion}%</strong><Progress value={stats.completion} label="Overall task completion" /></div></section>
    <section className="panel"><SectionHeading icon={<BookOpen size={18} />} title="Learning rhythm" to="/analytics" label="Analytics" /><div className="chart-summary"><strong>{duration(stats.weekly.reduce((sum, day) => sum + day.minutes, 0))}</strong><span className="small muted">last 7 days</span><Link className="tag" to="/time-tracking">Start a session <ArrowUpRight size={12} /></Link></div><Suspense fallback={<div className="chart loading">Loading chart…</div>}><StudyChart values={stats.weekly} /></Suspense>{!data.studySessions.length && <p className="small muted chart-note">Your first study session will bring this chart to life.</p>}</section>
    <section className="panel"><SectionHeading icon={<BookOpen size={18} />} title="Learning & building" to="/courses" label="View courses" />{data.courses.length || data.skills.length ? <div className="mini-progress-list">{[...data.courses.slice(0, 2).map(item => ({ item, kind: 'courses' as const })), ...data.skills.slice(0, 2).map(item => ({ item, kind: 'skills' as const }))].map(({ item, kind }) => <div key={item.id}><div><Link to={`/${kind}`}>{text(item, 'title')}</Link><span className="muted small">{entryProgress(item, kind)}%</span></div><Progress value={entryProgress(item, kind)} label={`${item.title} progress`} /></div>)}</div> : <EmptyState title="Invest in your future" description="Add a course or skill to track what you are learning." action={<Link className="text-link" to="/courses">Add a course <ArrowRight size={14} /></Link>} />}<div className="panel-footer inline"><Link to="/projects">{data.projects.filter(item => item.status === 'Active').length} active projects</Link><Link to="/habits">{stats.habitDone}/{data.habits.length} habits today</Link></div></section>
    <section className="panel"><SectionHeading icon={<Wallet size={18} />} title="Money this month" to="/finance" label="Overview" /><div className="finance-lines"><div><span className="muted">Income</span><strong className="success-text">{money(stats.income, data.settings.currency)}</strong></div><div><span className="muted">Expenses</span><strong>{money(stats.expense, data.settings.currency)}</strong></div><div><span className="muted">Savings</span><strong>{money(stats.savings, data.settings.currency)}</strong></div></div><div className="budget-callout"><span className="small muted">{budget ? `${money(budget, data.settings.currency)} in category budgets` : 'Give your spending a plan'}</span><Link className="text-link small" to="/finance/budget">{budget ? 'Review budgets' : 'Set a budget'} <ArrowRight size={14} /></Link></div></section>
    <section className="panel"><SectionHeading icon={<Flag size={18} />} title="On the horizon" to="/goals" label="All goals" />{deadlines.length ? <div className="deadline-list">{deadlines.map((item, index) => <Link key={index} to={item.to}><span className="date-tile"><strong>{Number(item.date.slice(8))}</strong><small>{new Date(`${item.date}T12:00:00`).toLocaleDateString(undefined, { month: 'short' })}</small></span><div><strong>{item.title}</strong><p className="small muted">{item.kind} · {item.date}</p></div><ArrowUpRight size={16} /></Link>)}</div> : <EmptyState title="Make the next milestone visible" description="Task, goal, and opportunity deadlines will appear here." />}</section>
    <section className="panel insight-panel"><div className="section-heading"><h2><Sparkles size={18} />A little perspective</h2><span className="tag">Local insight</span></div><p className="insight-copy">{localInsight(data)}</p><p className="small muted">Calculated from your records. No AI, no data sent anywhere.</p><Link className="text-link" to="/insights">Explore your insights <ArrowRight size={15} /></Link></section></div>
    <section className="panel information-strip"><div><h2><Compass size={19} />Stay curious. Stay informed.</h2><p className="muted small">Explore AI, software, and your next opportunity. External sources stay separate from your personal data.</p></div><Link className="button secondary" to="/information">Open information hub <ArrowUpRight size={16} /></Link></section>
    {adding && <EntryForm collection="tasks" onClose={() => setAdding(false)} />}
  </>
}
function Stat({ icon, label, value, detail, accent }: { icon: React.ReactNode; label: string; value: string; detail: string; accent: string }) {
  return <section className="panel stat"><div><span className="muted small">{label}</span><span className={`stat-icon ${accent}`}>{icon}</span></div><strong className="stat-value">{value}</strong><p className="muted small">{detail}</p></section>
}
function SectionHeading({ icon, title, to, label }: { icon: React.ReactNode; title: string; to: string; label: string }) {
  return <div className="section-heading"><h2>{icon}{title}</h2><Link to={to} className="muted small">{label} <ArrowUpRight size={13} /></Link></div>
}
