import { useEffect, useRef, useState } from 'react'
import { Bookmark, ExternalLink, RefreshCw, Search } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { getInformation, officialSources, type Article } from '../services/information'
import { newEntry, useStore } from '../data/store'
import { safeUrl } from '../data/model'
import { EmptyState, PageHeading } from '../components/ui'

const categories: Record<string, string> = { all: 'All', 'ai-ml': 'AI / ML', cse: 'CSE', software: 'Software Engineering', career: 'Career', 'study-abroad': 'Study Abroad', scholarships: 'Scholarships', competitions: 'Competitions', hackathons: 'Hackathons' }
export default function InformationPage() {
  const { category = 'all' } = useParams(), selected = categories[category] ?? 'All'
  const { data, save } = useStore()
  const [articles, setArticles] = useState<Article[]>([]), [errors, setErrors] = useState<string[]>([]), [loading, setLoading] = useState(false), [loaded, setLoaded] = useState(false), [query, setQuery] = useState('')
  const controller = useRef<AbortController | null>(null)
  useEffect(() => () => controller.current?.abort(), [])
  async function load() {
    controller.current?.abort(); const request = new AbortController(); controller.current = request; setLoading(true); setErrors([])
    const timeout = window.setTimeout(() => request.abort(), 15000)
    try { const result = await getInformation(request.signal); if (controller.current === request) { setArticles(result.articles); setErrors(result.errors); setLoaded(true) } }
    catch { if (controller.current === request) setErrors(['Could not retrieve information. Check your connection and try again.']) }
    finally { clearTimeout(timeout); if (controller.current === request) setLoading(false) }
  }
  const score = (article: Article) => data.settings.interests.reduce((sum, interest) => sum + (`${article.title} ${article.description} ${article.tags.join(' ')}`.toLowerCase().includes(interest.toLowerCase()) ? 1 : 0), 0)
  const visible = articles.filter(article => (selected === 'All' || article.category === selected) && `${article.title} ${article.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => score(b) - score(a) || b.publishedAt.localeCompare(a.publishedAt))
  const sources = officialSources.filter(source => selected === 'All' || source.category === selected)
  const opportunityCategory = ['Competitions', 'Hackathons', 'Study Abroad', 'Scholarships'].includes(selected)
  return <><PageHeading eyebrow="EXTERNAL INFORMATION" title={selected === 'All' ? 'Your information hub' : selected} description="Useful signals for your learning, career, and next opportunity." action={<Link className="button secondary" to="/read-later"><Bookmark size={16} />Read later</Link>} /><div className="category-tabs">{Object.entries(categories).map(([slug, label]) => <Link key={slug} className={selected === label ? 'active' : ''} to={`/information/${slug}`}>{label}</Link>)}</div><section className="privacy-note"><span className="tag">External sources</span><p>Fetching updates contacts public providers and sends no personal records. Interests rank results locally. Community articles are not verified advice.</p></section>
    <div className="section-heading"><h2>{opportunityCategory ? 'Official directories & organizers' : 'Start with trusted sources'}</h2><Link className="text-link small" to="/opportunities">Saved opportunities <ExternalLink size={13} /></Link></div><div className="source-grid">{sources.map(source => <a className="panel source-card" href={source.url} target="_blank" rel="noreferrer" key={source.url}><span className="eyebrow">{source.category}</span><h3>{source.title}<ExternalLink size={15} /></h3><p className="small muted">{source.description}</p><span className="source-domain">{new URL(source.url).hostname}</span></a>)}</div>
    {opportunityCategory ? <section className="panel"><EmptyState title="No verified event feed connected" description="Use the original directories above to find current opportunities, then save verified details and deadlines to your workspace. Listings above are sources, not active events or confirmed offers." action={<Link className="button secondary" to="/opportunities">Save an opportunity</Link>} /></section> : <><div className="section-heading feed-heading"><h2>Technology updates</h2><button className="button secondary" disabled={loading} onClick={() => void load()}><RefreshCw size={15} className={loading ? 'spin' : ''} />{loading ? 'Loading…' : loaded ? 'Refresh updates' : 'Fetch public updates'}</button></div><label className="search feed-search"><Search size={17} /><input aria-label="Search technology updates" placeholder="Search updates and tags…" value={query} onChange={e => setQuery(e.target.value)} /></label>{errors.map(error => <p role="status" className="notice" key={error}>{error}</p>)}{visible.length ? <div className="card-grid">{visible.map(article => <article className="panel article" key={article.id}><div className="tags"><span className="tag">{article.category}</span>{score(article) > 0 && <span className="tag green">Matches your interests</span>}</div><h3>{article.title}</h3><p className="muted small">{article.description}</p><div className="tags">{article.tags.slice(0, 4).map(tag => <span className="small muted" key={tag}>#{tag}</span>)}</div><p className="small muted">{article.source} · {article.publishedAt.slice(0, 10)}</p><div className="article-actions">{safeUrl(article.url) && <a className="text-link" href={safeUrl(article.url)} target="_blank" rel="noreferrer">Read source <ExternalLink size={14} /></a>}<button className="button secondary small" disabled={data.savedArticles.some(item => item.url === article.url)} onClick={() => void save('savedArticles', { ...newEntry(), title: article.title, description: article.description, url: article.url, source: article.source, category: article.category, publishedAt: article.publishedAt.slice(0, 10), tags: article.tags })}><Bookmark size={14} />{data.savedArticles.some(item => item.url === article.url) ? 'Saved' : 'Save'}</button></div></article>)}</div> : <section className="panel"><EmptyState title={loading ? 'Retrieving public updates…' : loaded ? 'No matching updates' : 'Fresh information, on your terms'} description={loaded ? 'Try another category or visit an original source above.' : 'Fetch updates when you want them. Results are cached in memory for 15 minutes; saved articles stay in your local backup.'} /></section>}</>}
  </>
}
